### ISSUE TITLE
Request: Fault Tolerance

### ISSUE THREAD

**Issue by basex** [moneta-rb/moneta#162]
If the backend is down, use the `:null` backend, instead of raising `
Redis::CannotConnectError` and similar exceptions.

Resouces:
- https://github.com/sorentwo/readthis#fault-tolerance

**Comment by asppsa** [comment]
Sounds good.  It could perhaps be implemented in the existing `Stack` wrapper ...

**Comment by asppsa** [comment]
@basex, there's a new wrapper in master called [Fallback](https://github.com/moneta-rb/moneta/blob/master/lib/moneta/fallback.rb) that hopefully does what you need. You can use it like so:

~~~ ruby
Moneta.build do
  use :Fallback, rescue: Redis::CannotConnectError # or Redis::BaseError
  adapter :Redis
~~~

The `rescue:` part tells the wrapper what errors to catch (by default it is `IOError`, which won't work for the Redis adapter), and it can also be a list if you want to get super-specific.  You can also add a block if you want to hand-craft the fallback adapter (instead of using `Null`).

If you are able to, it would be great if you could try this wrapper out and let me know what you think. Otherwise, I'll probably do a new release in a couple of days.

**Comment by basex** [comment]
@asppsa thanks a lot. I will test it and give you feedback.

**Comment by basex** [comment]
Thanks. Working as expected.
